# SPDX-FileCopyrightText: 2025 maxhash.io <dev@maxhash.io>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-license-headers:
    name: Lint License Headers
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: earthly/actions-setup@43211c7a0eae5344d6d79fb4aaf209c8f8866203 # v1.0.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.8.13
          use-cache: true
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: earthly --ci --github-annotations +lint-license-headers

  lint-go:
    name: Lint Go
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: earthly/actions-setup@43211c7a0eae5344d6d79fb4aaf209c8f8866203 # v1.0.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.8.13
          use-cache: true
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: earthly --ci --github-annotations +lint-go

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: earthly/actions-setup@43211c7a0eae5344d6d79fb4aaf209c8f8866203 # v1.0.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.8.13
          use-cache: true
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: earthly --ci --github-annotations --strict=false +build

